2024-01-26 23:51:26,442 [ERROR] main.views: Sequence.count() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 600, in get
    context['logs'] = logs.count()
                      ^^^^^^^^^^^^
TypeError: Sequence.count() missing 1 required positional argument: 'value'
2024-01-26 23:51:28,780 [ERROR] main.views: Sequence.count() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 600, in get
    context['logs'] = logs.count()
                      ^^^^^^^^^^^^
TypeError: Sequence.count() missing 1 required positional argument: 'value'
2024-01-26 23:51:47,991 [ERROR] main.views: Sequence.count() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 601, in get
    print(logs.count())
          ^^^^^^^^^^^^
TypeError: Sequence.count() missing 1 required positional argument: 'value'
2024-01-26 23:51:58,166 [ERROR] main.views: Sequence.count() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 602, in get
    print(logs.count())
          ^^^^^^^^^^^^
TypeError: Sequence.count() missing 1 required positional argument: 'value'
2024-01-26 23:52:42,433 [ERROR] main.views: 'int' object is not callable
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 599, in get
    print(logs_paginator.count())
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
2024-01-26 23:52:42,456 [ERROR] main.views: 'int' object is not callable
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 599, in get
    print(logs_paginator.count())
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
2024-01-27 00:09:08,918 [ERROR] main.views: That page contains no results
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 629, in get
    actions = actions_paginator.page(actions_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 71, in validate_number
    raise EmptyPage(self.error_messages["no_results"])
django.core.paginator.EmptyPage: That page contains no results
2024-01-27 00:09:10,847 [ERROR] main.views: That page contains no results
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 629, in get
    actions = actions_paginator.page(actions_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 71, in validate_number
    raise EmptyPage(self.error_messages["no_results"])
django.core.paginator.EmptyPage: That page contains no results
2024-01-27 00:09:15,889 [ERROR] main.views: That page contains no results
Traceback (most recent call last):
  File "C:\Users\majid\Desktop\stock\main\views.py", line 629, in get
    actions = actions_paginator.page(actions_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\majid\Desktop\stock\venv\Lib\site-packages\django\core\paginator.py", line 71, in validate_number
    raise EmptyPage(self.error_messages["no_results"])
django.core.paginator.EmptyPage: That page contains no results
